(in-package #:pg3)


(defparameter *desc-set-layout-create-info-value* '((:s-type (:descriptor-set-layout-create-info)
						     :p-next ((null-pointer))
						     :flags (*flags*)
						     :binding-count (*binding-count*)
						     :p-bindings (((:binding (0)
								   :descriptor-type (:uniform-buffer)
								   :descriptor-count (1)
								   :stage-flags ('(:vertex :fragment))
								   :p-immutable-samplers (((null-pointer)))
					  )))
						     )))

(defparameter *desc-pool-create-info-value* '((:s-type (:descriptor-pool-create-info)
					       :p-next ((null-pointer))
					       :flags (*flags*)
					       :max-sets (2)
					       :pool-size-count (1)
					       :p-pool-sizes (((:type (:uniform-buffer)
									:descriptor-count (2))
								       ))
					       )))

(defparameter *desc-alloc-info* '((:s-type (:descriptor-set-allocate-info)
				   :descriptor-pool (*descriptor-pool*)
				   :descriptor-set-count (*descriptor-set-count*)
				   :p-set-layouts ((*p-set-layouts*))
				   )))

(defparameter *write-desc-set* '((:s-type (:write-descriptor-set)
				  :dst-set (*descriptor-set*)
				  :dst-binding (0)
				  :dst-array-element (0)
				  :descriptor-type (:uniform-buffer)
				  :descriptor-count (1)
				  :p-buffer-info (((:buffer (*buffer*)
							    :offset (0)
							    :range (*buffer-size*)
						  )))
				  :p-image-info (nil)
				  :p-texel-buffer-view (((null-pointer)))
				  )))

